### ISSUE TITLE
获取资源方法不能使用

### ISSUE THREAD

**Issue by ponyfe** [nuptboyzhb/AndroidPluginFramework#7]
在第三课中，获取资源的时候会找不到相应的资源，总是返回0值，不知道这个是否成功的测试过？

**Comment by goldingking** [comment]
发现问题，如果新建了assetmanager，使用新建的assetmanager去加载apk中的资源，生成resource，替换原有的resource，那么resource中只有插件的资源，没有宿主的资源，宿主会报错。

我没有新建assetmanager，而是通过getAsset（）去获取， 报如下错误：

12-05 19:57:13.326 736-736/com.king.www.demos E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.king.www.demos, PID: 736
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.king.www.demos/com.king.www.demos.ui.plugin.PluginActivity}: android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/landscape.jpg from xml type layout resource ID #0x7f030001
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453)
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:173)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5579)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                 Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/landscape.jpg from xml type layout resource ID #0x7f030001
                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:3733)
                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:3680)
                                                                    at android.content.res.Resources.getLayout(Resources.java:2167)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                    at com.springnap.www.plugin.BlankFragment.onCreateView(BlankFragment.java:73)
                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
                                                                    at android.app.Activity.performStart(Activity.java:5461)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453) 
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:173) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5579) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: java.io.FileNotFoundException: Corrupt XML binary file
                                                                    at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                    at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:3711)
                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:3680) 
                                                                    at android.content.res.Resources.getLayout(Resources.java:2167) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                    at com.springnap.www.plugin.BlankFragment.onCreateView(BlankFragment.java:73) 
                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789) 
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955) 
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138) 
                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740) 
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501) 
                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551) 
                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177) 
                                                                    at android.app.Activity.performStart(Activity.java:5461) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453) 
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:173) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5579) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by goldingking** [comment]
我使用反射设置了mResources，但是在插件中依然调用宿主的资源
